image: riha-test-env

variables:
    ARTIFACT_NAME: "$CI_PROJECT_NAME.war"

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - mvn -DskipTests=true clean package
    artifacts:
        paths:
            - target/*.war
        expire_in: 1 mos
    tags:
        - riha

deploy_development:
    stage: deploy
    script:
        - echo "$SSH_PRIVATE_KEY" > id_rsa
        - chmod 700 id_rsa
        - mkdir $HOME/.ssh
        - echo "$SSH_HOST_KEY" > $HOME/.ssh/known_hosts
        - scp -i id_rsa target/*.war deployer@$SSH_HOST:$DEPLOYMENT_DIR/$ARTIFACT_NAME
    environment:
        name: demo
    when: manual
    tags:
        - riha