image: riha-test-env

variables:
    DEPLOYMENT_DIR: "/opt/tomcat/webapps"
    ARTIFACT_NAME: "$CI_PROJECT_NAME.war"

stages:
    - test
    - build
    - deploy

# Tests are failing. Commented for now
# test:
#     stage: test
#     script:
#         - mvn clean test
#     tags:
#         - riha

build:
    stage: build
    script:
        - mvn -DskipTests=true clean package
    artifacts:
        paths:
            - target/*.war
    tags:
        - riha

deploy_development:
    stage: deploy
    script:
        - echo "$SSH_PRIVATE_KEY" > id_rsa
        - chmod 700 id_rsa
        - mkdir $HOME/.ssh
        - echo "$SSH_HOST_KEY" > $HOME/.ssh/known_hosts
        - scp -i id_rsa target/*.war deployer@$SSH_HOST:$DEPLOYMENT_DIR/$ARTIFACT_NAME
    environment:
        name: development
        url: http://$SSH_HOST:$PORT/
    when: manual
    tags:
        - riha